import type { IsolationGitMetadata } from '../createIsolationGitMetadata';
import { extractJsonObjectText } from './extractJsonObjectText';
import { sanitizeGitSubject } from './sanitizeGitSubject';

/**
 * Что это: валидирует JSON от auxiliary model и приводит поля к безопасному git/PR контракту.
 * Зачем нужно: модель может вернуть лишние поля, многострочный subject или неполный JSON.
 * Какую продуктовую проблему решает: автоматически созданный PR получает аккуратные метаданные без риска сломать финализацию.
 */
export function normalizeGitMetadata({
  rawText,
  fallback
}: {
  rawText: string;
  fallback: IsolationGitMetadata;
}): IsolationGitMetadata {
  const parsed = parseMetadataJson({ rawText });
  if (!parsed) {
    return fallback;
  }

  const commitSubject = sanitizeGitSubject({
    value: typeof parsed.commitMessage === 'string' ? parsed.commitMessage : '',
    fallback: fallback.prTitle,
    maxLength: 72
  });
  const prTitle = sanitizeGitSubject({
    value: typeof parsed.prTitle === 'string' ? parsed.prTitle : commitSubject,
    fallback: commitSubject,
    maxLength: 90
  });
  const prBody = typeof parsed.prBody === 'string' && parsed.prBody.trim() ? parsed.prBody.trim() : fallback.prBody;

  return {
    commitMessage: `${commitSubject}\n\n${getCommitBody({ fallback })}`,
    prTitle,
    prBody,
    generatedByModel: true
  };
}

function parseMetadataJson({ rawText }: { rawText: string }): Record<string, unknown> | null {
  try {
    const parsed = JSON.parse(extractJsonObjectText({ rawText }));
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? (parsed as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function getCommitBody({ fallback }: { fallback: IsolationGitMetadata }): string {
  const body = fallback.commitMessage.split('\n').slice(1).join('\n').trim();
  return body || 'Generated by AIST isolated agent.';
}
